name: ci-plan
on:
  pull_request:
    branches: main

jobs:
  tf-plan:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform
    env:
      TF_IN_AUTOMATION: true
      AWS_REGION: eu-central-1
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (dev)
        id: plan
        run: terraform plan
